<?php
session_start();

$alertMessage = "";
$alertType = "";

if ($_SERVER["REQUEST_METHOD"] === "POST" && isset($_POST["send"])) {

    $to = "josephmwamuye5@gmail.com";

    $fullname = htmlspecialchars($_POST["fullname"]);
    $email = filter_var($_POST["email"], FILTER_SANITIZE_EMAIL);
    $company = htmlspecialchars($_POST["company"]);
    $phone = htmlspecialchars($_POST["phone"]);


    $headers = "From: {$fullname} <{$email}>\r\n";
    $headers .= "Reply-To: {$email}\r\n";
    $headers .= "Content-Type: text/plain; charset=UTF-8\r\n";

    $body = "A new user has joined the waiting list.\n\n";
$body .= "The following details were submitted:\n\n";
$body .= "Fullname: {$fullname}\n";
$body .= "Email: {$email}\n";
$body .= "Phone: {$phone}\n"; // If applicable
$body .= "Company: {$company}\n"; // If applicable
$body .= "Date Submitted: " . date("Y-m-d H:i:s") . "\n\n";
$body .= "Please follow up with this prospective user when onboarding becomes available.\n\n";
$body .= "This email was automatically generated by the website waiting list form.";

    if (mail($to, $subject, $body, $headers)) {
        $_SESSION["alertMessage"] = "Message sent successfully!";
        $_SESSION["alertType"] = "success";
    } else {
        $_SESSION["alertMessage"] = "Failed to send message.";
        $_SESSION["alertType"] = "danger";
    }

    header("Location: " . $_SERVER["PHP_SELF"]);
    exit();
}

if (isset($_SESSION["alertMessage"])) {
    $alertMessage = $_SESSION["alertMessage"];
    $alertType = $_SESSION["alertType"];

    unset($_SESSION["alertMessage"]);
    unset($_SESSION["alertType"]);
}
?>